[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "npm start"

[[edge_functions]]
function = "eleventy-edge"
path = "/"

# [[edge_functions]]
# function = "edge-two"
# path = "/"